#!/usr/bin/env bash
file_marker=/etc/encryptrootfs-initramfs

. /etc/dracut.conf.d/encryptrootfs.conf


_check_errors(){
   if [ $? -gt 0 ]
   then
        echo "Error during $1. Returned code is not 0 but '$?'"
        exit 1
   fi
}

_update_grub_config_centos7(){
    #avoiding lookup rootfs partition by UUID
    sed -i '/GRUB_DISABLE_LINUX_UUID/d' /etc/default/grub
    echo "GRUB_DISABLE_LINUX_UUID=\"true\"" >> /etc/default/grub

    #avoiding device autodetection by GRUB
    sed -i '/GRUB_DEVICE/d' /etc/default/grub
    echo "GRUB_DEVICE=\"/dev/${disk}\"" >> /etc/default/grub


    #generating new grub config
    grub2-mkconfig -o /boot/grub2/grub.cfg
    _check_errors "generating new grub config"
}

_update_grub_config_centos6(){
    sed -i -e "s@\(^\s*kernel.*\)\(root=UUID=[0-9a-f-]*\)@\1root=/dev/${disk}2@" /boot/grub/grub.conf
    sed -i -e "s@\(^\s*root\s\)(.*)@\1(hd0,1)@" /boot/grub/grub.conf
    sed -i -e "s@\(^\s*splashimage=\)(.*)@\1(hd0,1)@" /boot/grub/grub.conf
    _check_errors "Updating /boot/grub/grub.conf"
}

_install_grub_centos7(){
    grub2-install /dev/"$disk"
    _check_errors "installing grub to ${disk}"
}

_install_grub_centos6(){
    echo "MD5 of first 1024K of /dev/$disk before grub-install $(head --bytes=1024K /dev/"$disk" | md5sum)"
    grub-install --root-directory=/mnt/boot-partition hd0
    _check_errors "installing grub to ${disk}"
    echo "MD5 of first 1024K of /dev/$disk after grub-install $(head --bytes=1024K /dev/"$disk" | md5sum)"
}

_mount_boot_centos6(){
    #adding new mount point for boot partition
    mkdir -p /mnt/boot-partition
    echo "LABEL=${boot_partition_label}    /mnt/boot-partition  ${boot_partition_file_system}    defaults        1 1" >> /etc/fstab

    mount -a
    _check_errors "mounting boot device"
    mkdir /mnt/boot-partition/boot
    ln -s /mnt/boot-partition/boot /boot
}

_mount_boot_centos7(){
    mkdir /boot
    #adding new mount point for boot partition
    echo "LABEL=${boot_partition_label}    /boot  ${boot_partition_file_system}    defaults        1 1" >> /etc/fstab

    mount -a
    _check_errors "mounting boot device"
}
_check_linux_distrub(){
    if [ -x /usr/bin/lsb_release ] ; then
        OS="$(lsb_release -s -i | tr '[:upper:]' '[:lowe:]')"
        if [ "$OS" = "centos" ] ; then
            OSRELEASE="$(lsb_release -s -r | sed -e 's/\..*//')"
        else
            OSRELEASE="$(lsb_release -s -c)"
        fi
    elif [ -f /etc/redhat-release ] ; then
        OSRELEASE="$(grep -o -e "[0-9]" /etc/redhat-release | head -n 1)"
        OS="$(awk '{print tolower($1)}' /etc/redhat-release)"
    fi

    if [ -z "${OS}" ] || [ -z "${OSRELEASE}" ] ; then
         echo "Can't identify OS. Delected values OS=${OS} OSRELEASE=${OSRELEASE}"
         exit 1
    fi
}

if [ -f $file_marker ]
then
    echo "File-marker $file_marker found. Performing final modifications."
    set -x

    _check_linux_distrub

    [ -z "${boot_partition_label}" ] && boot_partition_label="boot"
    [ -z "${boot_partition_file_system}" ] && boot_partition_file_system="ext3"

    mv /boot/ /boot_
    _mount_boot_"$OS$OSRELEASE"

    #copying data
    cp -a /boot_/* /boot/
    rm -rf /boot_/

    _install_grub_"$OS$OSRELEASE"
    _update_grub_config_"$OS$OSRELEASE"

    rm -rf $file_marker
    _check_errors "removing file-marker $file_marker"
    set +x
else
    echo "No file-marker  '$file_marker' found. Assuming that all final actions were performed previously."
fi